version: '3.3'

networks:
    devnet:

services:
    devcontainer:
        build:
            dockerfile: Dockerfile
        networks: [devnet]
        ports: ["8080:8080"]
        command: sleep infinity


    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports: ["3306:3306"]
        networks: [devnet]
        volumes: [mariadb_data:/var/lib/mysql]

volumes:
    mariadb_data:
